### ISSUE TITLE
[Bug] 当proxy-providers使用type:inline时，proxy-groups的filter不生效

### ISSUE THREAD

**Issue by hooleez** [MetaCubeX/ClashX.Meta#131]
感谢你向 ClashX 提交 issue！
在提交之前，请确认：

- [x] 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] 这是 ClashX UI层面的问题，并非 Clash Core 的问题(例如xx软件连不上，无法连接特定服务器等)。其他 Clash 衍生版本没有次问题。
- [ ] 如果你可以自己 debug 并解决的话，提交 PR 吧！

请注意，如果你并没有遵照这个 issue template 填写内容，我们将直接关闭这个 issue。

我都确认过了，我要继续提交。

------------------------------------------------------------------

请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
proxy-providers:
  testpro:
    type: inline
    payload:
      - name: 美国-US-节点1
      - name: 美国-US-节点2
      - name: 日本-US-节点1

proxy-groups:
  - name: US (select)
     type: select
     filter: "美国"
     use:
       - testpro
```

### 环境 Environment
* 使用者的操作系统 (the OS running on the client)
macOS 15.4 (24E247)
* ClashX meta版本
v1.4.10 (577)

### 说明 Description
代理组中 filter: "美国"无法生效。
如果proxy-providers使用type: http/path，则filter能生效。
