### ISSUE TITLE
更新GEO数据库功能故障

### ISSUE THREAD

**Issue by pounod** [MetaCubeX/ClashX.Meta#25]
问题1:
通过面板功能手动更新GEO数据库时，会导致 .yaml 配置文件无法加载，并且无法自动恢复，仅能通过手动重载配置文件或重启客户端恢复。
1）功能面板1
<img width="411" alt="SCR-20230813-gziu" src="https://github.com/MetaCubeX/ClashX.Meta/assets/140609704/36391185-9988-4411-84ce-376671d5be92">

2）功能面板2
<img width="525" alt="SCR-20230813-gzpk" src="https://github.com/MetaCubeX/ClashX.Meta/assets/140609704/ba482227-8706-4cfd-80dd-a9d8a0cb7889">

问题2:
.yaml 配置文件配置了以下文件的获取地址，通过以上面板功能更新GEO数据库时，均不能完整更新以下几个文件（总会缺1、2个无法更新完整），可能由**问题1** 导致：
geosite.dat
geoip.dat
country.mmdb

```
geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
```
