### ISSUE TITLE
[Bug] Failed to list the proxies in the proxy group when group type is not 'select'

### ISSUE THREAD

**Issue by liouxy** [MetaCubeX/ClashX.Meta#88]
请附上任何可以帮助我们解决这个问题的信息，如果我们收到的信息不足，我们将对这个 issue 加上 *Needs more information* 标记并在收到更多资讯之前关闭 issue。

### clashX config

```
proxy-groups:
- name: 样例
  proxies:
  - 自动选择
  - 故障转移
  - 香港 01
  type: select
- name: 自动选择
  interval: 86400
  proxies:
  - 香港 01
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: 故障转移
  interval: 7200
  proxies:
  - 香港 01
  type: fallback
  url: http://www.gstatic.com/generate_204
```

### ClashX log

```
07/24/2024, 13:53:38.340  [info] ApiRequest.swift requestProxyProviderList(completeHandler:) requestProxyProviderList error Response could not be decoded because of error:
The data couldn’t be read because it isn’t in the correct format.
```

### ClashX Crash log

```
N/A
```

### 环境 Environment
……
* 使用者的操作系统 (the OS running on the client)
MACOS 15.0
* 网路环境或拓扑 (network conditions/topology)
N/A
* ISP 有没有进行 DNS 污染 (is your ISP performing DNS pollution?)
N/A
* 其他
……

### 重现问题的具体布骤 Steps to Reproduce

1. Add a new subscription using the `url-test` or `fallback` proxy group type.
2. View the list of proxies within the proxy group in the menu bar.

**我预期会发生……？**
It will list all the proxies in the proxy group.

**实际上发生了什麽？**
Just the first time after adding a new config or reloading the config, I can successfully view all the proxies. However, it fails after leaving the current window and clicking the menu bar button again. If I change the proxy group type to 'select', the problem does not occur. Therefore, I believe there is an issue with the function 'requestProxyProviderList' when the type is not 'select'.
